const fs=require('node:fs'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const html=fs.readFileSync(__dirname+'/public/index.html','utf8');
const d=JSON.parse(html.match(/<script id="dataset" type="application\/json">([\s\S]*?)<\/script>/)[1]);
const historical={nodes:d.sourceNodes.filter(n=>n.dates.some(day=>day<='2026-08-31')).map(n=>({...n,dates:n.dates.filter(day=>day<='2026-08-31'),sources:n.sources.filter(s=>s.date<='2026-08-31')})),links:d.sourceLinks.filter(l=>l.date<='2026-08-31')};
assert.equal(crypto.createHash('sha256').update(JSON.stringify(historical)).digest('hex'),'2ca56912b3cb2b30e1f11b211cea2d7b0749f604c2b24626106e9699195b31ae','六月至八月歷史不可變動');
assert.equal(d.dailyImports.length,2);const batch=d.dailyImports[0];
assert.equal(batch.date,'2026-09-09');assert.equal(batch.cutoff,'2026-09-09T21:00:20+08:00');
assert.equal(batch.browser_visits,515);assert.equal(batch.computer_events,2156);
assert.equal(batch.notes_read,21);assert.equal(batch.notes_imported,14);assert.equal(batch.private_notes_withheld,7);
assert.equal(batch.claude_sessions,2);assert.equal(batch.claude_entries,9);
assert.equal(d.days.length,94);assert.deepEqual(d.missing_dates,Array.from({length:8},(_,i)=>'2026-09-0'+(i+1)));
const today=d.nodes.filter(n=>n.dates.includes(batch.date));assert.equal(today.length,20);
assert.equal(today.filter(n=>n.level===3).length,8);
for(const id of ['footprint','reading-explore','device-admin','leisure-video'])assert(today.some(n=>n.id===id));
for(const label of ['文豪笑傳','字字珠璣','AI 輔助批改平台設計'])assert(!today.some(n=>n.label===label),'不能把圖譜回顧列到的舊專案算成今日工作');
assert(today.every(n=>new Set(n.sources.map(s=>s.date+'|'+s.kind)).size===n.sources.length));
for(const forbidden of ['合約','協商','畢方','購物車','付款方式','完成訂購','today-20260909-private','今天完整工時'])assert(!html.includes(forbidden));
assert(html.includes("requestedDate"));assert(html.includes("batch.date.slice(5)"));
console.log('通過：9/9 批次數量、20 今日節點／8 實踐、舊資料 hash 完整保留、8 天缺口、私人資訊排除、自我引用不灌水。');
