const fs=require('node:fs'),assert=require('node:assert/strict');
const html=fs.readFileSync(__dirname+'/public/index.html','utf8');
const d=JSON.parse(html.match(/<script id="dataset" type="application\/json">([\s\S]*?)<\/script>/)[1]);
assert.equal(d.start,'2026-06-01');assert.equal(d.until,'2026-08-31');
assert.equal(d.nodes.length,new Set(d.nodes.map(n=>n.id)).size);
const ids=new Set(d.nodes.map(n=>n.id));
assert(d.links.every(l=>ids.has(l.source)&&ids.has(l.target)));
assert(d.days.every(day=>day>=d.start&&day<=d.until));
assert(d.nodes.every(n=>n.dates.every(day=>day>=d.start&&day<=d.until)));
assert(d.links.every(l=>l.dates.every(day=>day>=d.start&&day<=d.until)));
assert.equal(d.days.length+d.missing_dates.length,92);
assert.equal(d.stats.claude_content_pending,0,'本次要求的 Claude 文件內容仍有未讀');
assert.equal(d.stats.claude_content_read,1097);
assert.equal(d.stats.claude_history_invalid,0);
assert.equal(d.stats.notes_imported,d.stats.claude_notes+d.stats.codex_notes);
assert(!html.includes('__DATA__'));
for(const forbidden of ['/Users/','private-source','private-work','claude.ai/chat','docs.google.com/','@gmail.com','sk-ant-','ghp_','gho_','-----BEGIN'])assert(!html.includes(forbidden),'公開檔案含敏感字樣：'+forbidden);
assert.deepEqual(fs.readdirSync(__dirname+'/public').sort(),['index.html']);
assert(d.nodes.flatMap(n=>n.sources).every(s=>!s.file.includes('://')&&!s.file.includes('.md')));
assert.equal(d.model,'life-work-v2');
assert.equal(d.themes.length,7);assert.equal(d.stats.keywords,19);
assert.equal(d.sourceNodes.length,83);assert.equal(d.sourceLinks.length,152);
assert(d.sourceNodes.some(n=>n.id==='claude'));
assert(!d.nodes.some(n=>n.kind==='工具'||n.id==='claude'));
assert(d.links.every(l=>l.source!=='claude'&&l.target!=='claude'));
assert.equal(d.nodes.filter(n=>n.id.startsWith('project-')).length,53,'原有具名專案不可遺失');
const visibleSource=html.slice(html.indexOf('function visible(){'),html.indexOf('function transform(){'));
const inputs={'#month':{value:'all'},'#search':{value:''}};
const getView=(focus=null,key=null)=>new Function('D','$','focus','key',visibleSource+';return visible()')(d,s=>inputs[s],focus,key);
assert.equal(getView().ns.length,26,'總覽只應顯示重心與關鍵字');
assert.equal(getView().ls.length,19);
assert(getView('learning','key-feedback').ns.some(n=>n.id==='grading'));
assert(getView('lead','key-habits').ns.some(n=>n.label==='自我領導力環島棋'));
for(const month of ['2026-06','2026-07','2026-08']){inputs['#month'].value=month;assert(getView().ns.length>0)}
inputs['#month'].value='all';inputs['#search'].value='文豪';assert(getView().ns.some(n=>n.label==='文豪笑傳'));
inputs['#search'].value='Claude';assert.equal(getView().ns.length,0,'工具不可重新變成圖上節點');
console.log('通過：7 重心／19 關鍵字、53 專案保留、來源不遺失、工具不入主圖、分層展開、搜尋與月份、日期及隱私。');
