const fs=require('node:fs'),assert=require('node:assert/strict');
const html=fs.readFileSync(__dirname+'/public/index.html','utf8');
const d=JSON.parse(html.match(/<script id="dataset" type="application\/json">([\s\S]*?)<\/script>/)[1]);
assert.equal(d.start,'2026-06-01');assert.equal(d.until,'2026-08-31');
assert.equal(d.nodes.length,new Set(d.nodes.map(n=>n.id)).size);
const ids=new Set(d.nodes.map(n=>n.id));
assert(d.links.every(l=>ids.has(l.source)&&ids.has(l.target)));
assert(d.days.every(day=>day>=d.start&&day<=d.until));
assert(d.nodes.every(n=>n.dates.every(day=>day>=d.start&&day<=d.until)));
assert(d.links.every(l=>l.dates.every(day=>day>=d.start&&day<=d.until)));
assert.equal(d.days.length+d.missing_dates.length,92);
assert.equal(d.stats.claude_content_pending,0,'本次要求的 Claude 文件內容仍有未讀');
assert.equal(d.stats.claude_content_read,1097);
assert.equal(d.stats.claude_history_invalid,0);
assert.equal(d.stats.notes_imported,d.stats.claude_notes+d.stats.codex_notes);
assert(!html.includes('__DATA__'));
for(const forbidden of ['/Users/','private-source','private-work','claude.ai/chat','docs.google.com/','@gmail.com','sk-ant-','ghp_','gho_','-----BEGIN'])assert(!html.includes(forbidden),'公開檔案含敏感字樣：'+forbidden);
assert.deepEqual(fs.readdirSync(__dirname+'/public').sort(),['index.html']);
assert(d.nodes.flatMap(n=>n.sources).every(s=>!s.file.includes('://')&&!s.file.includes('.md')));
console.log('通過：92 天日期邊界、Claude 內容全讀、索引數量、節點連線、公開目錄白名單與敏感資訊掃描。');
